2025-01-10 13:36:01,342 - INFO - Starting Server...
2025-01-10 13:36:01,342 - INFO - Starting Client...
2025-01-10 13:36:01,377 - ERROR - Client [ERROR]: python: can't open file 'D:\\Source Code\\Magang Kalbe\\Raspberry Pi\\clientdb.py': [Errno 2] No such file or directory
2025-01-10 13:36:01,378 - ERROR - Server [ERROR]: python: can't open file 'D:\\Source Code\\Magang Kalbe\\Raspberry Pi\\masterserver.py': [Errno 2] No such file or directory
2025-01-10 13:37:46,946 - INFO - Starting Server...
2025-01-10 13:37:46,947 - INFO - Starting Client...
2025-01-10 13:37:46,996 - ERROR - Client [ERROR]: python: can't open file 'D:\\Source Code\\Magang Kalbe\\Raspberry Pi\\tryclientdb.py': [Errno 2] No such file or directory
2025-01-10 13:37:46,996 - ERROR - Server [ERROR]: python: can't open file 'D:\\Source Code\\Magang Kalbe\\Raspberry Pi\\tryserver.py': [Errno 2] No such file or directory
2025-01-10 13:39:02,893 - INFO - Starting Server...
2025-01-10 13:39:02,894 - INFO - Starting Client...
2025-01-10 13:39:02,939 - ERROR - Client [ERROR]: python: can't open file 'D:\\Source Code\\Magang Kalbe\\Raspberry Pi\\tryclientdb.py': [Errno 2] No such file or directory
2025-01-10 13:39:02,947 - ERROR - Server [ERROR]: python: can't open file 'D:\\Source Code\\Magang Kalbe\\Raspberry Pi\\tryserver.py': [Errno 2] No such file or directory
2025-01-10 13:39:23,553 - INFO - Starting Server...
2025-01-10 13:39:23,554 - INFO - Starting Client...
2025-01-10 13:40:34,054 - INFO - Client: Serial FAILED: could not open port 'COM3': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-01-10 13:40:34,054 - INFO - Client: Serial FAILED: could not open port 'COM3': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-01-10 13:40:34,054 - INFO - Client: Serial FAILED: could not open port 'COM3': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-01-10 13:40:34,054 - INFO - Client: Serial FAILED: could not open port 'COM3': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-01-10 13:40:34,054 - INFO - Client: Serial FAILED: could not open port 'COM3': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-01-10 13:40:34,054 - INFO - Client: Serial connection established. 2025-01-10 13:39:25
2025-01-10 13:40:34,055 - INFO - Client: Data sent: {'id': 0, 'h_value': 11.6, 'd_value': 18.13, 't_value': 5.7, 'status': 'N', 'code_instrument': 'A20230626002', 'time_series': '3', 'time_insert': '13:40:00', 'created_date': '2025-01-10'}
2025-01-10 13:40:34,217 - ERROR - Client [ERROR]: D:\Source Code\Magang Kalbe\Raspberry Pi\socket\tryclientdb.py:20: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
2025-01-10 13:40:34,217 - ERROR - Client [ERROR]: Base = declarative_base()
2025-01-10 13:40:34,217 - ERROR - Client [ERROR]: Traceback (most recent call last):
2025-01-10 13:40:34,217 - ERROR - Client [ERROR]: File "D:\Source Code\Magang Kalbe\Raspberry Pi\socket\tryclientdb.py", line 347, in <module>
2025-01-10 13:40:34,217 - ERROR - Client [ERROR]: time.sleep(1)
2025-01-10 13:40:34,217 - ERROR - Client [ERROR]: KeyboardInterrupt
